"""Canonical production driver for Paper 1 Models 1-3.

Models
------
Model 1: Baseline Translational Representation
    Gravity only; point-mass projectile.

Model 2: Aerodynamic Fidelity
    Gravity + Theis et al. (2026) natural-hail drag in a stationary,
    constant reference atmosphere.

Model 3: Environmental Fidelity
    Gravity + the same Theis drag, but with altitude-dependent atmosphere
    and an ambient wind profile.

No Results are hard-coded. All reported values are generated by this driver.
"""
from __future__ import annotations

from dataclasses import dataclass
from math import acos, exp, pi, sqrt, degrees
from pathlib import Path
import csv

import numpy as np
from scipy.integrate import solve_ivp

G = 9.80665
R_AIR = 287.05287
P0 = 101325.0
T0 = 288.15
LAPSE = -0.0065
SEA_LEVEL_RHO = 1.225
# Sutherland-law constants for air.
MU_REF = 1.716e-5
T_REF = 273.15
SUTHERLAND = 111.0

D_IN = np.array([1.00, 1.25, 1.50, 1.75, 2.00, 2.50, 3.00, 3.25])
NOMINAL_HEIGHT_M = 1000.0
NOMINAL_WIND_MPS = 33.3
ROOF_PITCHES_DEG = [15.0, 30.0, 45.0]
RHO_HAIL = 790.0


@dataclass(frozen=True)
class Atmosphere:
    rho: float
    mu: float


def standard_atmosphere(z_m: float) -> Atmosphere:
    """U.S. Standard Atmosphere troposphere, with Sutherland viscosity."""
    z = float(np.clip(z_m, 0.0, 11000.0))
    T = T0 + LAPSE * z
    p = P0 * (T / T0) ** (-G / (LAPSE * R_AIR))
    rho = p / (R_AIR * T)
    mu = MU_REF * (T / T_REF) ** 1.5 * (T_REF + SUTHERLAND) / (T + SUTHERLAND)
    return Atmosphere(rho=rho, mu=mu)


def constant_reference_atmosphere() -> Atmosphere:
    return standard_atmosphere(0.0)


def wind_velocity(model: int, z_m: float) -> float:
    return 0.0 if model < 3 else NOMINAL_WIND_MPS


def theis_sphericity(Dmax_cm: float) -> float:
    return 1.0 - 0.025 * Dmax_cm**1.24


def theis_cd_continuous(Re: float, Dmax_cm: float) -> tuple[float, str]:
    """Theis et al. (2026) continuous drag formulation.

    Returns the drag coefficient and an evidence status. Values outside the
    reported Re/Psi domain are flagged rather than hidden.
    """
    Re = max(float(Re), 1e-12)
    psi = theis_sphericity(Dmax_cm)
    supported = (1e1 <= Re <= 1e5) and (psi > 0.67)
    status = "supported" if supported else "extrapolative"

    CD0_gr = 0.58
    delta0 = 6.27
    a = 6000.0
    b = 2.15
    c = -1.19

    CD0 = 0.52 / psi
    m_psi = b + c * psi
    CDgr = CD0_gr * (1.0 + (delta0 / sqrt(Re)) ** 2)
    h = exp(-((Re / a) ** m_psi))
    cd = CDgr * h + CD0 * (1.0 - h)
    return float(cd), status


def hail_mass_kg(D_m: float) -> float:
    """Equivalent-volume spherical mass for Models 1-3."""
    volume = pi / 6.0 * D_m**3
    return RHO_HAIL * volume


def drag_force_components(vx: float, vz: float, wind_x: float, atm: Atmosphere, D_m: float) -> tuple[float, float, float, float, str]:
    vrel_x = vx - wind_x
    vrel_z = vz
    vrel = float(np.hypot(vrel_x, vrel_z))
    if vrel < 1e-12:
        return 0.0, 0.0, 0.0, 0.0, "supported"
    D_cm = D_m * 100.0
    Re = atm.rho * vrel * D_m / atm.mu
    cd, status = theis_cd_continuous(Re, D_cm)
    q = 0.5 * atm.rho * vrel**2
    A = pi * D_m**2 / 4.0
    Fd = q * cd * A
    Fx = -Fd * vrel_x / vrel
    Fz = -Fd * vrel_z / vrel
    return Fx, Fz, vrel, Re, status


def rhs(model: int, release_height: float, D_m: float):
    m = hail_mass_kg(D_m)
    atm0 = constant_reference_atmosphere()

    def f(_t, y):
        x, z, vx, vz = y
        if model == 1:
            Fx = 0.0
            Fz = -m * G
        else:
            atm = atm0 if model == 2 else standard_atmosphere(z)
            wx = wind_velocity(model, z)
            Fdx, Fdz, _, _, _ = drag_force_components(vx, vz, wx, atm, D_m)
            Fx = Fdx
            Fz = Fdz - m * G
        return np.array([vx, vz, Fx / m, Fz / m], dtype=float)

    return f


def run_descent(model: int, D_in: float, release_height_m: float) -> dict:
    D_m = D_in * 0.0254
    f = rhs(model, release_height_m, D_m)
    y0 = np.array([0.0, release_height_m, 0.0, 0.0], dtype=float)

    def event_ground(_t, y):
        return y[1]

    event_ground.terminal = True
    event_ground.direction = -1

    sol = solve_ivp(
        f,
        (0.0, max(120.0, 2.0 * release_height_m / 10.0 + 120.0)),
        y0,
        events=event_ground,
        rtol=1e-9,
        atol=1e-11,
        max_step=0.05,
    )
    if sol.t_events[0].size == 0:
        raise RuntimeError(f"Model {model} did not reach target for {D_in} in at {release_height_m} m")

    t_imp = float(sol.t_events[0][0])
    x, z, vx, vz = sol.y_events[0][0]
    V = float(np.hypot(vx, vz))

    # At impact, define the incoming direction toward the roof as -v.
    # Roof outward normal for a positive-pitch surface is n=(-sin(phi), cos(phi)).
    # Incidence is the angle between -v and the outward surface normal.
    return {
        "model": f"Model {model}",
        "diameter_in": D_in,
        "Dmax_m": D_m,
        "release_height_m": release_height_m,
        "wind_mps": NOMINAL_WIND_MPS if model == 3 else 0.0,
        "impact_time_s": t_imp,
        "impact_x_mps": vx,
        "impact_z_mps": vz,
        "V_impact_mps": V,
        "status": "supported" if model in (1, 2) else "sensitivity",
    }


def add_incidence_rows(base_rows: list[dict]) -> list[dict]:
    out = []
    for row in base_rows:
        if row["model"] != "Model 3":
            continue
        vx = row["impact_x_mps"]
        vz = row["impact_z_mps"]
        incoming = np.array([-vx, -vz], dtype=float)
        norm_in = np.linalg.norm(incoming)
        if norm_in == 0:
            continue
        for pitch in ROOF_PITCHES_DEG:
            phi = np.deg2rad(pitch)
            n = np.array([-np.sin(phi), np.cos(phi)])
            c = float(np.clip(np.dot(incoming / norm_in, n), -1.0, 1.0))
            angle = degrees(acos(c))
            rec = dict(row)
            rec["roof_pitch_deg"] = pitch
            rec["incidence_angle_deg"] = angle
            out.append(rec)
    return out


def main() -> None:
    out_dir = Path("/mnt/data")
    production_path = out_dir / "paper1_models1_3_production.csv"
    height_path = out_dir / "paper1_models1_3_height_convergence.csv"
    incidence_path = out_dir / "paper1_models1_3_incidence.csv"
    metadata_path = out_dir / "paper1_models1_3_production_metadata.txt"

    base_rows: list[dict] = []
    for D_in in D_IN:
        for model in (1, 2, 3):
            base_rows.append(run_descent(model, float(D_in), NOMINAL_HEIGHT_M))

    for row in base_rows:
        # add the actual impact relative-air state for Models 2-3
        D_m = row["Dmax_m"]
        atm = constant_reference_atmosphere() if row["model"] == "Model 2" else standard_atmosphere(0.0)
        wx = row["wind_mps"]
        vrel = float(np.hypot(row["impact_x_mps"] - wx, row["impact_z_mps"]))
        Re = 0.0 if vrel == 0 else atm.rho * vrel * D_m / atm.mu
        cd, aero_status = (0.0, "not_applicable") if row["model"] == "Model 1" else theis_cd_continuous(Re, D_m * 100.0)
        row["Re_impact"] = Re
        row["psi_impact"] = theis_sphericity(D_m * 100.0) if row["model"] != "Model 1" else np.nan
        row["Cd_impact"] = cd
        row["aero_evidence_status"] = aero_status
        row["mass_kg"] = hail_mass_kg(D_m)

    # Height convergence: Model 2 and Model 3 at 100 m to 10 km.
    heights = [100.0, 250.0, 500.0, 1000.0, 3000.0, 5000.0, 7000.0, 10000.0]
    height_rows: list[dict] = []
    for D_in in D_IN:
        for H in heights:
            for model in (2, 3):
                r = run_descent(model, float(D_in), H)
                r["Re_impact"] = np.nan
                r["psi_impact"] = theis_sphericity(r["Dmax_m"] * 100.0)
                height_rows.append(r)

    # Relative changes for the main production comparison.
    by_key = {(r["diameter_in"], r["model"]): r for r in base_rows}
    for r in base_rows:
        D = r["diameter_in"]
        v1 = by_key[(D, "Model 1")]["V_impact_mps"]
        v2 = by_key[(D, "Model 2")]["V_impact_mps"]
        v3 = by_key[(D, "Model 3")]["V_impact_mps"]
        r["dV_1to2_pct"] = (v2 - v1) / v1 * 100.0
        r["dV_2to3_pct"] = (v3 - v2) / v2 * 100.0
        r["dV_1to3_pct"] = (v3 - v1) / v1 * 100.0
        r["roof_pitch_deg"] = np.nan
        r["incidence_angle_deg"] = np.nan

    incidence_rows = add_incidence_rows(base_rows)

    def write_csv(path: Path, rows: list[dict]) -> None:
        fields = sorted({k for row in rows for k in row.keys()})
        with path.open("w", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(f, fieldnames=fields)
            writer.writeheader()
            writer.writerows(rows)

    write_csv(production_path, base_rows)
    write_csv(height_path, height_rows)
    write_csv(incidence_path, incidence_rows)

    with metadata_path.open("w", encoding="utf-8") as f:
        f.write("Paper 1 Models 1-3 canonical production run\n")
        f.write("Models: 1 gravity only; 2 Theis natural-hail drag in constant stationary atmosphere; 3 same drag + altitude-varying atmosphere + 33.3 m/s uniform horizontal wind.\n")
        f.write("Diameters (in): " + ", ".join(f"{x:.2f}" for x in D_IN) + "\n")
        f.write(f"Nominal height (m): {NOMINAL_HEIGHT_M}\n")
        f.write(f"Nominal hail density (kg/m^3): {RHO_HAIL}\n")
        f.write("Roof pitches for incidence table (deg): " + ", ".join(map(str, ROOF_PITCHES_DEG)) + "\n")
        f.write("Model 3 evidence status is a sensitivity condition because the nominal 33.3 m/s wind is a prescribed environmental sensitivity, not a measured hail-storm field realization.\n")
        f.write("No Model 4 or Model 5 quantities are included in these production files.\n")
        f.write("Incidence-angle rows for Model 3 are written to paper1_models1_3_incidence.csv for the three roof pitches.\n")

    # Human-readable summary for quick audit.
    print(f"Wrote {production_path}")
    print(f"Wrote {height_path}")
    print(f"Wrote {incidence_path}")
    print(f"Wrote {metadata_path}")
    print("Nominal production comparison:")
    for D_in in D_IN:
        rows = [r for r in base_rows if r["diameter_in"] == float(D_in)]
        print(
            f"{D_in:>4.2f} in | "
            + " | ".join(f"{r['model']}: {r['V_impact_mps']:.4f} m/s" for r in rows)
            + " | "
            + f"dV1-2={rows[1]['dV_1to2_pct']:.2f}% dV2-3={rows[2]['dV_2to3_pct']:.2f}%"
        )


if __name__ == "__main__":
    main()
