"""
Paper 1 - Final Progressive Hail-Impact Modeling Framework
===========================================================

Purpose
-------
This module is the consolidated engineering specification for the Paper 1
interactive simulation. It is intentionally transparent about what is
literature-supported, what is a controlled modeling assumption, and what
remains unresolved.

Core progression
----------------
Model 1: Baseline translational representation
Model 2: Aerodynamic fidelity
Model 3: Environmental / finite-height fidelity
Model 4: Rigid-body Euler fidelity + lift + aerodynamic moment + contact-point kinematics

Common contact layer
--------------------
Normal contact: Sun et al. (2015) nonlinear viscoelastic hail-contact law.
Tangential contact: conditional friction model; dynamic hailstone-shingle mu is
not claimed as a measured material property and must remain a sensitivity input.

Important scope boundaries
--------------------------
- Unmelted hail only; no melting/ablation/growth model is included.
- Roofing structural deformation/failure is outside Paper 1.
- Primary simulations should be restricted to experimentally characterized
  aerodynamic parameter space; extrapolative cases must be flagged.
- List et al. (1973) coefficient curves are working plot digitizations, not
  exact tabulated data. They provide selected slices, not a complete 3-D
  C_D(Re,theta,chi), C_L(Re,theta,chi), C_M(Re,theta,chi) surface.
- Theis et al. (2026) natural-hail drag is preferred for natural-hail C_D in the
  Newton regime, with its stated validity limits. Their continuous Eq. (18)
  formulation is available for lower Re in its reported regime.
- Fully coupled sub-millisecond contact feedback into Euler rotation remains
  an open numerical/mechanics question and is NOT silently represented as
  solved in this module.

Primary references used in this module
--------------------------------------
1. List R, et al. 1973. On the aerodynamics of spheroidal hailstone models.
2. Kry PR, List R. 1974. Aerodynamic torques on rotating oblate spheroids.
3. Kry PR, List R. 1974. Angular motions of freely falling spheroidal hailstone models.
4. Matson RJ, Huggins AW. 1980. The direct measurement of the sizes, shapes and
   kinematics of falling hailstones.
5. Sun J, Lam N, Zhang L, Ruan D, Gad E. 2015. Contact forces generated by
   hailstone impact.
6. Heymsfield A, et al. 2020. Corrigendum to the 2018 hail terminal-velocity,
   mass-flux, and kinetic-energy study.
7. Lin Y, Kumjian MR, Soderholm J, Giammanco I. 2024. Modeling nonspherical hailstones.
8. Theis A, et al. 2026. A Wind Tunnel Investigation into the Aerodynamics of
   Natural Hailstones.

Notes for the interactive simulation
-------------------------------------
The code favors explicit status metadata over silent extrapolation. For Figma,
these statuses should map to visible UI states such as:
  "supported", "interpolated", "extrapolative", or "open question".
"""

from __future__ import annotations

from dataclasses import dataclass, asdict
from enum import Enum
from math import atan2, cos, exp, pi, sin, sqrt
from typing import Any, Dict, Optional, Tuple

import numpy as np

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
G = 9.80665                 # m/s^2
R_AIR = 287.05287           # J/(kg K)
P0 = 101325.0               # Pa
T0 = 288.15                 # K
LAPSE = -0.0065             # K/m, troposphere baseline
MU_AIR_20C = 1.7894e-5      # Pa s; baseline only


class EvidenceStatus(str, Enum):
    SUPPORTED = "supported"
    INTERPOLATED = "interpolated"
    EXTRAPOLATIVE = "extrapolative"
    UNSUPPORTED = "unsupported"
    SENSITIVITY = "sensitivity"
    OPEN_QUESTION = "open_question"


@dataclass(frozen=True)
class AtmosphereState:
    z_m: float
    T_K: float
    p_Pa: float
    rho_kg_m3: float
    mu_air_Pa_s: float


@dataclass(frozen=True)
class WindProfile:
    """Controlled wind profile for trajectory sensitivity."""
    kind: str = "calm"
    u0_mps: float = 0.0
    u_top_mps: float = 0.0
    z_top_m: float = 10000.0

    def velocity(self, z_m: float) -> np.ndarray:
        z = max(0.0, float(z_m))
        if self.kind == "calm":
            return np.array([0.0, 0.0], dtype=float)
        if self.kind == "uniform":
            return np.array([self.u0_mps, 0.0], dtype=float)
        if self.kind == "linear_shear":
            f = np.clip(z / self.z_top_m, 0.0, 1.0)
            return np.array([self.u0_mps + f * (self.u_top_mps - self.u0_mps), 0.0], dtype=float)
        raise ValueError(f"Unknown wind profile: {self.kind}")


@dataclass(frozen=True)
class HailGeometry:
    """Oblate-spheroid geometry using maximum dimension as major diameter."""
    Dmax_m: float
    aspect_ratio: float
    density_kg_m3: float = 790.0

    @property
    def volume_m3(self) -> float:
        # V = pi/6 * Dmax^3 * chi for an oblate spheroid.
        return (pi / 6.0) * self.aspect_ratio * self.Dmax_m**3

    @property
    def mass_kg(self) -> float:
        return self.density_kg_m3 * self.volume_m3

    @property
    def inertia_major_kgm2(self) -> float:
        # List et al. spheroid convention:
        # I = m D^2 (1 + chi^2) / 20 about the symmetry/major-axis direction.
        return self.mass_kg * self.Dmax_m**2 * (1.0 + self.aspect_ratio**2) / 20.0


@dataclass(frozen=True)
class ContactLawResult:
    kn_N_m_p: float
    p: float
    cor: float
    damping_Dn: float
    velocity_status: EvidenceStatus
    source: str = "Sun et al. (2015)"


@dataclass(frozen=True)
class ImpactState:
    impact_speed_mps: float
    impact_vx_mps: float
    impact_vz_mps: float
    gamma_rad: float
    omega_rads: float
    beta_rad: float
    normal_velocity_mps: float
    tangential_velocity_mps: float
    tangential_velocity_increment_mps: float
    aero_status: EvidenceStatus


# ---------------------------------------------------------------------------
# Atmosphere
# ---------------------------------------------------------------------------

def standard_atmosphere(z_m: float) -> AtmosphereState:
    """U.S. Standard Atmosphere troposphere baseline (0-11 km)."""
    z = float(np.clip(z_m, 0.0, 11000.0))
    T = T0 + LAPSE * z
    p = P0 * (T / T0) ** (-G / (LAPSE * R_AIR))
    rho = p / (R_AIR * T)
    # Baseline viscosity; replace with Sutherland law if needed for high-precision Re.
    return AtmosphereState(z, T, p, rho, MU_AIR_20C)


# ---------------------------------------------------------------------------
# Natural-hail shape / drag: Theis et al. (2026)
# ---------------------------------------------------------------------------

def theis_sphericity(Dmax_cm: float) -> float:
    """Theis et al. 2026 Eq. (22): Psi = 1 - 0.025 Dmax^1.24."""
    D = float(Dmax_cm)
    return 1.0 - 0.025 * D**1.24


def theis_cd_newton(Dmax_cm: float, method: str = "power") -> Tuple[float, EvidenceStatus]:
    """Natural-hail Newton-regime drag, Theis et al. 2026 Eqs. (8)-(9).

    Validity reported by Theis for the present natural-hail Newton-regime data:
    Re ~ 1e4 to 1e5 and 0.67 < Psi <= 1 for the fitted sphericity data.
    """
    psi = theis_sphericity(Dmax_cm)
    status = EvidenceStatus.SUPPORTED if psi > 0.67 else EvidenceStatus.EXTRAPOLATIVE
    if method == "power":
        cd = 0.52 / psi
    elif method == "linear":
        cd = -0.75 * psi + 1.25
    else:
        raise ValueError("method must be 'power' or 'linear'")
    return cd, status


def theis_cd_continuous(Re: float, Dmax_cm: float) -> Tuple[float, EvidenceStatus]:
    """Theis et al. 2026 continuous Eq. (18)-style formulation.

    This combines a graupel branch with the natural-hail Newton branch and is
    intended by Theis et al. for roughly 1e1 <= Re <= 1e5 and 0.67 < Psi <= 1.
    """
    Re = max(float(Re), 1e-12)
    psi = theis_sphericity(Dmax_cm)
    status = EvidenceStatus.SUPPORTED if psi > 0.67 and 1e1 <= Re <= 1e5 else EvidenceStatus.EXTRAPOLATIVE

    # Fitted constants from Theis et al. 2026 Eqs. (18)-(21).
    CD0_gr = 0.58
    delta0 = 6.27
    a = 6000.0
    b = 2.15
    c = -1.19

    # Newton-limit natural-hail term from Eq. (9).
    CD0 = 0.52 / psi
    m_psi = b + c * psi

    # Graupel branch (Eq. 19) as given in the paper.
    # The published form is represented here as CD0_gr * [1 + (delta0 / sqrt(Re))^2].
    CDgr = CD0_gr * (1.0 + delta0 / sqrt(Re)) ** 2
    h = exp(-((Re / a) ** m_psi))
    cd = CDgr * h + CD0 * (1.0 - h)
    return float(cd), status


# ---------------------------------------------------------------------------
# List et al. (1973) aerodynamic coefficient interface
# ---------------------------------------------------------------------------

class List73Interface:
    """Interface for the working List et al. (1973) plot-digitized data.

    The actual digitized CSVs are maintained separately. This wrapper is kept
    intentionally conservative: unsupported coefficient combinations are not
    silently fabricated.
    """

    def __init__(self, working_data: Optional[Dict[str, Any]] = None):
        self.working_data = working_data or {}

    def coefficient_status(self, quantity: str, Re: float, theta_deg: float, chi: float) -> EvidenceStatus:
        # Conservative metadata-only implementation for the interactive model.
        # Exact lookups should use the maintained digitized CSV layer.
        if not (4e4 <= Re <= 4e5):
            return EvidenceStatus.EXTRAPOLATIVE
        if not (0.50 <= chi <= 0.79):
            return EvidenceStatus.EXTRAPOLATIVE
        if quantity == "CD":
            supported = (abs(chi - 0.50) < 1e-9) or any(abs(theta_deg - t) < 1e-9 for t in (0.0, 45.0, 90.0))
        elif quantity in ("CL", "CM"):
            supported = (abs(chi - 0.50) < 1e-9) or abs(theta_deg - 45.0) < 1e-9
        else:
            supported = False
        return EvidenceStatus.SUPPORTED if supported else EvidenceStatus.UNSUPPORTED


# ---------------------------------------------------------------------------
# Sun et al. (2015) nonlinear viscoelastic normal contact law
# ---------------------------------------------------------------------------

def sun2015_contact_parameters(v_imp_mps: float) -> ContactLawResult:
    """Sun et al. 2015 velocity-correlated contact parameters.

    kn is in kN/m^p in the source correlations; returned here in SI N/m^p.
    Their velocity-parametric calibration is based on 50-mm spherical SHI,
    with the parametric study spanning approximately 7.9-29.1 m/s.
    """
    v = float(v_imp_mps)
    kn = (2.200 * v + 170.269) * 1e3
    p = 0.010 * v + 1.263
    cor = max(-0.001 * v + 0.049, 1e-4)
    status = (
        EvidenceStatus.SUPPORTED
        if 7.9 <= v <= 29.1
        else EvidenceStatus.EXTRAPOLATIVE
    )
    # D_n = (0.2p+1.3) * ((1-COR)/COR) * k_n / delta_dot_0.
    # delta_dot_0 is supplied during impact initialization.
    return ContactLawResult(kn, p, cor, np.nan, status)


def sun2015_damping_Dn(kn_N_m_p: float, p: float, cor: float, delta_dot0_mps: float) -> float:
    """Generalized Sun et al. (2015) damping coefficient relationship."""
    if delta_dot0_mps <= 0.0:
        raise ValueError("delta_dot0_mps must be positive")
    return (0.2 * p + 1.3) * ((1.0 - cor) / cor) * kn_N_m_p / delta_dot0_mps


def sun2015_normal_force(delta_m: float, delta_dot_mps: float, law: ContactLawResult) -> float:
    """F_n = D_n delta^p delta_dot + k_n delta^p.

    D_n must already be supplied/calculated for the current impact event.
    """
    if delta_m <= 0.0:
        return 0.0
    elastic = law.kn_N_m_p * delta_m ** law.p
    viscous = law.damping_Dn * delta_m ** law.p * max(delta_dot_mps, 0.0)
    return float(max(0.0, elastic + viscous))


# ---------------------------------------------------------------------------
# Contact kinematics / conditional tangential friction
# ---------------------------------------------------------------------------

def contact_point_velocity(vG: np.ndarray, omega_vec: np.ndarray, r_vec: np.ndarray) -> np.ndarray:
    """Rigid-body contact-point velocity: v_c = v_G + omega x r."""
    return np.asarray(vG, dtype=float) + np.cross(np.asarray(omega_vec, dtype=float), np.asarray(r_vec, dtype=float))


def decompose_contact_velocity(v_contact: np.ndarray, normal_unit: np.ndarray) -> Tuple[float, np.ndarray, float]:
    """Return normal scalar, tangential vector, and tangential magnitude."""
    n = np.asarray(normal_unit, dtype=float)
    n = n / np.linalg.norm(n)
    v = np.asarray(v_contact, dtype=float)
    vn = float(np.dot(v, n))
    vt_vec = v - vn * n
    return vn, vt_vec, float(np.linalg.norm(vt_vec))


def conditional_tangential_force(mu: float, Fn: float, vt_vec: np.ndarray) -> np.ndarray:
    """Sliding-limit Coulomb force; no claim that mu is experimentally known.

    This is a conditional sensitivity calculation only. A fully coupled stick-slip
    interface model is intentionally left outside the current Paper 1 framework.
    """
    vt = float(np.linalg.norm(vt_vec))
    if vt <= 0.0 or Fn <= 0.0:
        return np.zeros(3)
    return -float(mu) * float(Fn) * np.asarray(vt_vec, dtype=float) / vt


# ---------------------------------------------------------------------------
# Model evidence specification for UI / manuscript consistency
# ---------------------------------------------------------------------------

MODEL_EVIDENCE = {
    "Model 1": {
        "added_physics": ["center-of-mass translation", "gravity"],
        "source_basis": ["Newtonian particle representation"],
        "primary_outputs": ["trajectory", "impact speed", "global-force baseline"],
        "status": EvidenceStatus.SUPPORTED.value,
    },
    "Model 2": {
        "added_physics": ["aerodynamic drag", "natural-hail C_D option"],
        "source_basis": ["Theis et al. 2026", "List et al. 1973"],
        "primary_outputs": ["impact speed", "Re", "drag force"],
        "status": EvidenceStatus.SUPPORTED.value,
    },
    "Model 3": {
        "added_physics": ["finite release height", "altitude-varying atmosphere", "wind profile"],
        "source_basis": ["U.S. Standard Atmosphere baseline", "trajectory literature"],
        "primary_outputs": ["impact state as a function of fall history"],
        "status": EvidenceStatus.SENSITIVITY.value,
    },
    "Model 4": {
        "added_physics": ["lift", "aerodynamic moment", "Euler rotation", "contact-point kinematics"],
        "source_basis": ["List et al. 1973", "Kry & List 1974", "Matson & Huggins 1980", "Lin et al. 2024", "Theis et al. 2026"],
        "primary_outputs": ["omega", "gamma", "beta", "v_contact", "v_t"],
        "status": EvidenceStatus.SUPPORTED.value,
        "limitations": [
            "List coefficient data are selected slices, not a complete 3-D surface",
            "low-angle C_M behavior is incompletely published",
            "unsupported chi/Re/theta combinations must be flagged",
            "fully coupled contact-feedback rotation is unresolved",
        ],
    },
    "Common contact": {
        "added_physics": ["nonlinear viscoelastic normal contact", "conditional tangential friction"],
        "source_basis": ["Sun et al. 2015"],
        "primary_outputs": ["F_n(t)", "indentation", "conditional F_t(t)"],
        "status": EvidenceStatus.SUPPORTED.value,
        "limitations": [
            "Sun calibration is spherical simulated hail ice, not a roof assembly",
            "velocity-correlated parameters are calibrated over 7.9-29.1 m/s",
            "hailstone-shingle dynamic mu is not directly measured",
        ],
    },
}


# ---------------------------------------------------------------------------
# Sensitivity defaults
# ---------------------------------------------------------------------------

DEFAULT_SENSITIVITY = {
    "density_kg_m3": [700.0, 790.0, 900.0],
    "aspect_ratio_percentiles": ["P25", "P50", "P75"],
    "fall_height_m": [100.0, 250.0, 500.0, 1000.0, 3000.0],
    "rotational_K": [0.55, 0.60, 0.67, 0.75, 0.90],
    "friction_mu": [0.10, 0.20, 0.40, 0.60, 0.80],
    "wind_profiles": ["calm", "uniform", "linear_shear"],
}


# ---------------------------------------------------------------------------
# Example user-facing summary for Figma integration
# ---------------------------------------------------------------------------

def simulation_metadata() -> Dict[str, Any]:
    return {
        "scope": {
            "unmelted_hail_only": True,
            "roof_structural_response_included": False,
            "fully_coupled_contact_feedback_solved": False,
        },
        "evidence_status_definitions": {
            "supported": "within published experimental/model parameter range",
            "interpolated": "interpolated between supported measurements",
            "extrapolative": "outside published range; shown only as explicit sensitivity",
            "unsupported": "no defensible published interpolation path",
            "sensitivity": "controlled uncertainty parameter, not a measured universal constant",
            "open_question": "identified but not solved in the present implementation",
        },
        "key_outputs": [
            "impact speed",
            "normal velocity",
            "tangential velocity",
            "rotation rate",
            "orientation",
            "beta",
            "peak normal force",
            "normal impulse",
            "maximum indentation",
            "conditional tangential force",
        ],
        "model_evidence": MODEL_EVIDENCE,
        "sensitivity_defaults": DEFAULT_SENSITIVITY,
    }


if __name__ == "__main__":
    print("Paper 1 final framework loaded.")
    print("Scope:", simulation_metadata()["scope"])
    print("Models:", ", ".join(MODEL_EVIDENCE.keys()))
